version: "3.9"

services:

  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      #- "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_MY_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/letsencrypt:/letsencrypt"
    depends_on:
      - server
      - database
    ports:
      - 80:80
      - 443:443

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start:server"]
    volumes:
      - /usr/src/app
    environment:
      APP_ENV: ${APP_ENV}
      COOKIE_SECRET: ${COOKIE_SECRET}
      SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SIGNING_SECRET: ${STRIPE_WEBHOOK_SIGNING_SECRET}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.${PRIMARY_DOMAIN}`)"
      - "traefik.http.services.admin.loadbalancer.server.port=3000"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls.certresolver=myresolver"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start:worker"]
    volumes:
      - /usr/src/app
    depends_on:
      - server
      - database
    environment:
      APP_ENV: ${APP_ENV}
      COOKIE_SECRET: ${COOKIE_SECRET}
      SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SIGNING_SECRET: ${STRIPE_WEBHOOK_SIGNING_SECRET}
  
  storefront:
    build:
      context: ./storefront/
      dockerfile: Dockerfile.storefront
      args:
        STOREFRONT_VERSION: 0.1.27
    environment:
      SERVER_API_HOST: https://admin.${PRIMARY_DOMAIN}
      SERVER_API_PORT: 443
      SERVER_API_PATH: shop-api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storefront.rule=Host(`${PRIMARY_DOMAIN}`)"
      - "traefik.http.services.storefront.loadbalancer.server.port=4000"
      - "traefik.http.routers.storefront.entrypoints=websecure"
      - "traefik.http.routers.storefront.tls.certresolver=myresolver"
      
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  db-data:
    external: true