version: "3.9"

services:

  traefik:
      image: traefik:v2.9
      container_name: traefik
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./files/traefik.toml:/etc/traefik/traefik.toml
      depends_on:
        - server
        - database
      ports:
        - 8080:8080
        - 80:80
        - 443:443

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start:server"]
    volumes:
      - /usr/src/app
    environment:
      APP_ENV: ${APP_ENV}
      COOKIE_SECRET: ${COOKIE_SECRET}
      SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    labels:
        - "traefik.http.routers.admin.rule=Host(`admin.${PRIMARY_DOMAIN}`)"
        - "traefik.http.services.admin.loadbalancer.server.port=3000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["yarn", "start:worker"]
    volumes:
      - /usr/src/app
    environment:
      APP_ENV: ${APP_ENV}
      COOKIE_SECRET: ${COOKIE_SECRET}
      SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
  
  storefront:
    build:
      context: .
      dockerfile: Dockerfile.storefront
      args:
        STOREFRONT_VERSION: 0.1.27
    environment:
      SERVER_API_HOST: http://server
      SERVER_API_PORT: 3000
      SERVER_API_PATH: shop-api
    labels:
      - "traefik.http.routers.storefront.rule=Host(`${PRIMARY_DOMAIN}`)"
      - "traefik.http.services.storefront.loadbalancer.server.port=4000"
  
  database:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  db-data:
    external: true